export enum ActionTypes {
  // API Tracking ------------------------------------------------->

  API_REQUEST_START = 'API_REQUEST_START',
  API_REQUEST_COMPLETE = 'API_REQUEST_COMPLETE',
  API_REQUEST_ERROR = 'API_REQUEST_ERROR',
  API_CLEAR_ERRORS = 'API_CLEAR_ERRORS',
  // Home ------------------>
  GET_HOME_PAGE_REQUEST = 'GET_HOME_PAGE_REQUEST',
  GET_HOME_PAGE_SUCCESS = 'GET_HOME_PAGE_SUCCESS',
  GET_HOME_PAGE_FAILURE = 'GET_HOME_PAGE_FAILURE'
}